app/Model/Hotel.php
=> create Hotel Model

app/Model/Hotel.php
=> update Hotel Model namespace

resources/views/admin/admin-hotel/index.blade.php
#27 
fix form adit to tag a in file admin/admin-hotel/index.blade.php
=> convert form edit to tag a

app/RoomType.php, database/migrations/2015_09_22_094629_create_room_type_table.php
#30 create model and migration file for RoomType
=> issue_30 create model and migration file for RoomType

resources/views/hotel/partials/footer.blade.php, resources/views/hotel/partials/header.blade.php, resources/views/hotel/partials/navbar.blade.php, resources/views/hotel/partials/sidebar.blade.php, resources/views/layouts/hotel.blade.php
=> issue_42 Create hotel management template and layout

app/HotelRoomType.php, database/migrations/2015_10_08_080112_create_hotel_room_types_table.php
#32 
create migration and model hotel room type
=> issue_32, create migration and model hotel room tyoe

app/AdminHotel.php, app/Http/Controllers/Hotel/AuthController.php, app/Http/Kernel.php, app/Http/Middleware/Hotel/Authenticate.php, app/Http/Middleware/Hotel/RedirectIfAuthenticated.php, app/Http/Requests/Hotel/LoginRequest.php, app/Http/Routes/hotel_routes.php, config/auth.php, database/seeds/AdminHotelTableSeeder.php, resources/lang/en/messages.php, resources/views/hotel/auth/login.blade.php, resources/views/layouts/hotel/partials/flash.blade.php, tests/admin-auth/AuthControllerTest.php, tests/hotel-auth/AuthControllerTest.php, tests/hotel-auth/HotelAuthControllerTest.php
=> issue_45 Create hotel admin login page

app/Http/Controllers/Admin/AuthController.php, app/Http/Kernel.php, app/Http/Middleware/Admin/RedirectIfAuthenticated.php
- sync
- used in Admin/AuthControler
- rename to admin.guest in Kernel
=> Create Admin/RedirectIfAuthenticated in middleware

app/User.php, database/migrations/2014_10_12_000000_create_users_table.php
=> issue_52 Create User migration & Model

resources/views/frontend/partials/footer.blade.php, resources/views/frontend/partials/header.blade.php, resources/views/frontend/partials/navbar.blade.php, resources/views/frontend/partials/slider.blade.php, resources/views/layouts/frontend.blade.php
=> fixes #59 - Create master page and partials for frontend page

app/Http/Routes/admin_routes.php
=> issue_50 Set prefix for admin routes

app/Http/Controllers/Admin/AdminUserController.php, app/Http/Routes/admin_routes.php
=> Rename UserController to AdminUserController #72

.gitignore, public/uploads/.gitignore
=> add .gitignore in uploads #71

resources/views/admin/errors/404.blade.php, resources/views/frontend/errors/404.blade.php, resources/views/hotel/errors/404.blade.php
#77 
add 404 error pages
Fixes #77
=> add 404 error pages

app/CheckIn.php, app/Order.php, database/migrations/2015_10_15_021321_create_orders_table.php, database/migrations/2015_10_15_022342_create_checkins_table.php
#83 
- create migration/model order and checkin
- closed #83
=>  #83 create migration/model order and checkin

app/Http/Controllers/Frontend/AuthController.php, app/Http/Controllers/Frontend/FrontendBaseController.php, app/Http/Requests/Frontend/RegisterRequest.php, app/Http/Routes/frontend_routes.php, public/assets/js/preview_image.js, resources/lang/en/messages.php, resources/views/frontend/auth/register.blade.php, resources/views/frontend/partials/header.blade.php, tests/user-auth/UserAuthControllerTest.php
=> Fix #70 User register

circle.yml, phpmd.xml
=> fix circle.yml

app/Http/Controllers/Frontend/ProfileController.php, app/Http/Requests/Frontend/ProfileRequest.php, app/Http/Routes/frontend_routes.php, resources/lang/en/messages.php, resources/views/frontend/profile/profile.blade.php, tests/user/UserProfileTest.php
#53 
- Create file profile.blade.php
-Create controller ProfileController.php
- Fixed #53
=> #53 issue_53

app/Http/Controllers/Admin/AdminBaseController.php, app/Http/Controllers/Hotel/HotelBaseController.php, app/Http/Routes/hotel_routes.php, resources/views/frontend/partials/header.blade.php
=> fix issue_97

resources/views/hotel/partials/sidebar.blade.php
=> fix issue 97
